name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🛠 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'dependencies'
      - 'security'
  - title: '🏗️ GitHub actions'
    labels:
      - 'ci'
      - 'github-actions'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
commitish: 'main'
exclude-labels:
  - "ignore-for-release"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'chore'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/i"
      - "/docs/i"
  - label: 'github-actions'
    title:
      - "/github actions/i"
      - "/ci/i"
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - "/bug/i"
      - "/fix/i"
  - label: 'feature'
    title:
      - "/feat/i"
template: |
  ## Changes

  $CHANGES