name: Test changes

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
    branches:
      - main
  workflow_dispatch:

jobs:
  enforce-label:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "feature,bug,maintenance,dependencies,chore,ignore-for-release,major,minor,patch,github-actions"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['feature','bug','maintenance', 'dependencies', 'chore', 'ignore-for-release', 'major', 'minor', 'patch', 'github-actions']"

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: 📥 Restore dependencies
        run: dotnet restore --verbosity normal
      - name: 🔨 Build
        run: dotnet build --no-restore --verbosity normal
      - name: 📋 Test
        run: dotnet test --no-restore --verbosity normal
